#pragma once

#include "HexFF/ReaderDriver.h"

namespace HexFF {

/**
 * Scaled 24 volts monitor
 * Real voltage is computed using voltage ratio generated by the voltage divider.
 */
class VoltageDriver : public BasePinReaderDriver<double> {
 public:
  VoltageDriver(uint8_t _pin, double _volt_ratio);

  const char* getName() override;

  double operator()() const override;

 protected:
  double volt_ratio_;  // Voltage ratio
};

//=======

class FactoryVoltageDriver {
 public:
  static VoltageDriver* create(const char* t_name, const JsonVariant& t_settings, const JsonVariant& t_extra_settings);

 private:
  static inline bool s_registered = FactoryDriver::add("Voltage", create);
};

}  // namespace HexFF